### PR TITLE
Hide menu on Esc, and onBlur. Actually hide it.

### LINKED ISSUE #14: blur does not hide the menu
In version 3.01 (with elm 0.17) the menu is not hidden if the focus is removed. Selecting an item still hides the menu so I guess the "onBlur" in the div is not working anymore.

### PR DESCRIPTION
**Pull request by maximsch2**
Hopefully fixes #14 and #18

### CODE REVIEW

File: src/Autocomplete.elm [hunk 1]
```diff
@@ -171,7 +171,7 @@ updateModel msg model =
         ( { model | selectedItemIndex = boundedNewIndex }, { defaultStatus | selectionChanged = True } )
 
     ShowMenu bool ->
-      ( { model | showMenu = bool }, defaultStatus )
+      ( { model | showMenu = bool }, {defaultStatus | completed = not bool})
```
Comment (gregziegan) [inline src/Autocomplete.elm:174]: I don't think the `completed` status should change, since toggling the menu is accessible via `showMenu`. `completed` should only be `True` when a completion code is toggled, like the default code: the `tab` key.

So in other words, this Msg type `ShowMenu` will not affect whether the autocomplete is completed. Your Elm app can always call a helper function `getCurrentValue` to see if the current value matches something in the provided item list.

**Comment by gregziegan** [comment]
Thanks for this @maximsch2! Small but important fix. If you remove that `complete = not bool`, I'll go ahead and merge! (Or we can discuss further if my comment wasn't clear / you think I'm wrong)

**Comment by maximsch2** [comment]
I agree that `completed = not bool` is probably a hack, but without it the menu never goes away, this is actually the most important part.

**Comment by gregziegan** [comment]
I figured out a solution by updating the `update` function, I'll make a PR after merging this one! It'll resolve the one issue with your PR that is:

When clicking on an item, the blur event fires for the input field, and the text is not filled in
